### ISSUE TITLE
Material UI Navbar

### ISSUE THREAD

**Issue by nischal619** [nischal619/daraz2.0#1]
Add material ui and material ui icons in the project
create header / navbar using material ui

nav bar should look like this: 
daraz 2.0 ---------------------- home, products, about us, ----- search bar here ------ cart icon -- login icon ---

**Comment by sambhavgupta0705** [comment]
Hey ,I can work on this issue.

**Comment by kafle1** [comment]
Hey nischal,
I have been working with material ui and would like to contribute in your project.
Thanks
