### ISSUE TITLE
Create Product Card UI

### ISSUE THREAD

**Issue by nischal619** [nischal619/daraz2.0#3]
Create new product card ui using material ui in ./components/ProductCard.jsx file

the product card should contain image, name, price, add to cart icon button

**Comment by yadavsairaj** [comment]
Hey can i work on this issue?

**Comment by ChaudharyRaman** [comment]
Hi @yadavsairaj , i would like to work on this issue. can you assign it to me?

**Comment by kafle1** [comment]
Hey nischal,
I have experience in creating product cards.
Can you please assign this to me. 
I would love to contribute <3
