### ISSUE TITLE
Footer 

### ISSUE THREAD

**Issue by nischal619** [nischal619/daraz2.0#4]
Create a footer using material ui in ./components/Footer.jsx file

footer should contain name of project, copyright, and some naviation links and social links like fb, twitter etc

**Comment by sambhavgupta0705** [comment]
Hey ,I can wokr on this issue,please assign it to me.

**Comment by sambhavgupta0705** [comment]
hey ,Any Updates?

**Comment by ChaudharyRaman** [comment]
Hi @nischal619 , I would like to work on this issue. can you assign it to me?

**Comment by sambhavgupta0705** [comment]
Hey ,any Updates???

**Comment by kafle1** [comment]
hey nischal, i would like to work on this issue. Thanks ;)
