### ISSUE TITLE
Carousel of images and offers

### ISSUE THREAD

**Issue by nischal619** [nischal619/daraz2.0#5]
create a Carousel below the nav bar of the site 
use react query package to get the images from this site

Random
> https://source.unsplash.com/random

Size
> https://source.unsplash.com/300x300

Search term
> https://source.unsplash.com/random/?productivity,city

**Comment by Tusharjain123** [comment]
Hey can I work on this issue?

**Comment by Tusharjain123** [comment]
Hey can I work on this issue?

**Comment by pscon** [comment]
Hey, I just saw your issue @nischal619 , and I would love to help you on this one !

**Comment by kafle1** [comment]
Hey @nischal619  i would like to work on this issue
